---
# more strict version to catch leftover `console.log` etc.
extends:
  - './base.yaml'
rules:
  no-console:
    - 1
    - allow:
      - warn
      - error
  no-debugger: 1
  func-names: 1
  prefer-arrow-callback: 1
